### ISSUE TITLE
Pictures problem

### ISSUE THREAD

**Issue by Stormwine2003** [DmitrySerg/COVID-19#3]
Excuse me, but your pictures looks like disabled. Could you upload it again, please? I'm really interested in this project.

**Comment by DmitrySerg** [comment]
@Stormwine2003 Hi! Could you, please, clarify, which pictures seem to be disabled?

**Comment by Stormwine2003** [comment]
Sorry,I forgot where my computer is these days. I do think that all pictures that in your file 'picture' are disabled. The part of picture in your page is well. I'll appriciate it if you could load them again, or we could exchange our Wechat number. BTW,Are you Chinese?May be we could talk in Chinese. Thank you.

**Comment by Stormwine2003** [comment]
Sorry, I click the wrong place. Please ask me follow this comment
